resources:

- name: godog-test
  type: git
  source:
    uri: https://github.com/danieljamesrees/godog_test.git
    git_config:
    - name: user.email
      value: daniel.james.rees.finkit@gmail.com
    - name: user.name
      value: FINkit
- name: buildstack-bbl-state
  type: git
  source:
    uri: ((buildstack-bbl-state.uri))
    branch: master
    username: ((buildstack-bbl-state.username))
    password: ((buildstack-bbl-state.password))

jobs:

- name: test-buildstack-job
  serial: true
  plan:
  - get: godog-test
    trigger: true
  - get: buildstack-bbl-state
  - task: test-buildstack-task
    config:
      platform: linux
      inputs:
      - name: godog-test
      - name: buildstack-bbl-state
      image_resource:
        type: docker-image
        source: { repository: 'datacore/alpine-golang', version: '1.9' }
      run:
        path: godog-test/ci/scripts/test_buildstack.sh
      params:
        JUMPBOX_ADDRESS: ((jumpbox-address))
        JUMPBOX_PRIVATE_KEY: ((ssh-key))
        CREDHUB_USERNAME: ((credhub-username))
        CREDHUB_PASSWORD: ((credhub-password))
        CREDHUB_PROXY_PORT: ((credhub-proxy-port))
